export type ProjectPlatform = "Amazon" | "Temu" | "Tmall" | "TikTok" | "Shopify";

export type ProjectStatus = "Draft" | "Working" | "Completed" | "Archived";

export interface Project {
  id: string;
  name: string;
  description: string;
  platform: ProjectPlatform;
  language: string;
  status: ProjectStatus;
  createdAt: string;
  updatedAt: string;
  coverImage: string;
  thumbnail: string;
  productCount: number;
  imageCount: number;
}

export const mockProjects: Project[] = [
  {
    id: "project-001",
    name: "Summer Skincare Launch",
    description: "Hero visuals for a seasonal skincare product collection.",
    platform: "Tmall",
    language: "Chinese",
    status: "Working",
    createdAt: "2026-05-18",
    updatedAt: "2026-06-26",
    coverImage: "placeholder-skincare",
    thumbnail: "thumbnail-skincare",
    productCount: 18,
    imageCount: 64,
  },
  {
    id: "project-002",
    name: "Premium Coffee Gift Set",
    description: "Marketplace product visuals for a boxed coffee bundle.",
    platform: "Amazon",
    language: "English",
    status: "Completed",
    createdAt: "2026-05-12",
    updatedAt: "2026-06-25",
    coverImage: "placeholder-coffee",
    thumbnail: "thumbnail-coffee",
    productCount: 8,
    imageCount: 42,
  },
  {
    id: "project-003",
    name: "Smart Desk Campaign",
    description: "Lifestyle image direction for smart office furniture.",
    platform: "TikTok",
    language: "English",
    status: "Draft",
    createdAt: "2026-06-01",
    updatedAt: "2026-06-24",
    coverImage: "placeholder-desk",
    thumbnail: "thumbnail-desk",
    productCount: 6,
    imageCount: 19,
  },
  {
    id: "project-004",
    name: "Home Storage Refresh",
    description: "Clean product grid visuals for storage accessories.",
    platform: "Temu",
    language: "English",
    status: "Working",
    createdAt: "2026-05-30",
    updatedAt: "2026-06-23",
    coverImage: "placeholder-storage",
    thumbnail: "thumbnail-storage",
    productCount: 24,
    imageCount: 88,
  },
  {
    id: "project-005",
    name: "Athleisure Capsule",
    description: "Studio and lifestyle visuals for a capsule apparel launch.",
    platform: "Shopify",
    language: "English",
    status: "Completed",
    createdAt: "2026-04-28",
    updatedAt: "2026-06-22",
    coverImage: "placeholder-athleisure",
    thumbnail: "thumbnail-athleisure",
    productCount: 32,
    imageCount: 126,
  },
  {
    id: "project-006",
    name: "Kitchen Essentials Set",
    description: "A+ style images for bundled kitchen tools.",
    platform: "Amazon",
    language: "English",
    status: "Archived",
    createdAt: "2026-03-14",
    updatedAt: "2026-06-20",
    coverImage: "placeholder-kitchen",
    thumbnail: "thumbnail-kitchen",
    productCount: 14,
    imageCount: 51,
  },
  {
    id: "project-007",
    name: "Beauty Device Upgrade",
    description: "Premium visual system for compact beauty devices.",
    platform: "Tmall",
    language: "Chinese",
    status: "Working",
    createdAt: "2026-06-04",
    updatedAt: "2026-06-19",
    coverImage: "placeholder-beauty",
    thumbnail: "thumbnail-beauty",
    productCount: 10,
    imageCount: 37,
  },
  {
    id: "project-008",
    name: "Outdoor Lighting Line",
    description: "Night scene imagery for garden and patio lighting.",
    platform: "Temu",
    language: "English",
    status: "Draft",
    createdAt: "2026-06-06",
    updatedAt: "2026-06-18",
    coverImage: "placeholder-lighting",
    thumbnail: "thumbnail-lighting",
    productCount: 21,
    imageCount: 45,
  },
  {
    id: "project-009",
    name: "Pet Care Starter Pack",
    description: "Friendly e-commerce visuals for pet care bundles.",
    platform: "TikTok",
    language: "English",
    status: "Working",
    createdAt: "2026-05-22",
    updatedAt: "2026-06-17",
    coverImage: "placeholder-pet",
    thumbnail: "thumbnail-pet",
    productCount: 15,
    imageCount: 58,
  },
  {
    id: "project-010",
    name: "Minimal Jewelry Drop",
    description: "Elegant product detail images for jewelry launch assets.",
    platform: "Shopify",
    language: "English",
    status: "Completed",
    createdAt: "2026-04-19",
    updatedAt: "2026-06-16",
    coverImage: "placeholder-jewelry",
    thumbnail: "thumbnail-jewelry",
    productCount: 28,
    imageCount: 92,
  },
  {
    id: "project-011",
    name: "Travel Organizer Series",
    description: "Conversion-oriented imagery for travel accessories.",
    platform: "Amazon",
    language: "English",
    status: "Working",
    createdAt: "2026-05-25",
    updatedAt: "2026-06-15",
    coverImage: "placeholder-travel",
    thumbnail: "thumbnail-travel",
    productCount: 16,
    imageCount: 73,
  },
  {
    id: "project-012",
    name: "Baby Care Promotion",
    description: "Soft visual direction for baby care product bundles.",
    platform: "Tmall",
    language: "Chinese",
    status: "Draft",
    createdAt: "2026-06-08",
    updatedAt: "2026-06-14",
    coverImage: "placeholder-baby",
    thumbnail: "thumbnail-baby",
    productCount: 11,
    imageCount: 24,
  },
  {
    id: "project-013",
    name: "Fitness Gear Bundle",
    description: "Marketplace assets for compact home workout products.",
    platform: "TikTok",
    language: "English",
    status: "Completed",
    createdAt: "2026-04-07",
    updatedAt: "2026-06-13",
    coverImage: "placeholder-fitness",
    thumbnail: "thumbnail-fitness",
    productCount: 19,
    imageCount: 81,
  },
  {
    id: "project-014",
    name: "Desk Accessory Refresh",
    description: "Clean office scenes for small desktop accessories.",
    platform: "Temu",
    language: "English",
    status: "Archived",
    createdAt: "2026-03-27",
    updatedAt: "2026-06-12",
    coverImage: "placeholder-accessory",
    thumbnail: "thumbnail-accessory",
    productCount: 22,
    imageCount: 69,
  },
  {
    id: "project-015",
    name: "Luxury Candle Collection",
    description: "Warm brand imagery for scented candle collections.",
    platform: "Shopify",
    language: "English",
    status: "Working",
    createdAt: "2026-05-16",
    updatedAt: "2026-06-11",
    coverImage: "placeholder-candle",
    thumbnail: "thumbnail-candle",
    productCount: 13,
    imageCount: 46,
  },
  {
    id: "project-016",
    name: "Portable Blender Launch",
    description: "Bright visuals for portable kitchen appliance listings.",
    platform: "Amazon",
    language: "English",
    status: "Draft",
    createdAt: "2026-06-10",
    updatedAt: "2026-06-10",
    coverImage: "placeholder-blender",
    thumbnail: "thumbnail-blender",
    productCount: 7,
    imageCount: 18,
  },
  {
    id: "project-017",
    name: "Festival Gift Campaign",
    description: "Seasonal gift visuals for cross-platform commerce.",
    platform: "Tmall",
    language: "Chinese",
    status: "Working",
    createdAt: "2026-05-08",
    updatedAt: "2026-06-09",
    coverImage: "placeholder-gift",
    thumbnail: "thumbnail-gift",
    productCount: 35,
    imageCount: 104,
  },
  {
    id: "project-018",
    name: "Eco Cleaning Products",
    description: "Fresh marketplace assets for household cleaning products.",
    platform: "Temu",
    language: "English",
    status: "Completed",
    createdAt: "2026-04-02",
    updatedAt: "2026-06-08",
    coverImage: "placeholder-cleaning",
    thumbnail: "thumbnail-cleaning",
    productCount: 20,
    imageCount: 78,
  },
  {
    id: "project-019",
    name: "Phone Case Trend Set",
    description: "Fast-turnaround visuals for phone case trend testing.",
    platform: "TikTok",
    language: "English",
    status: "Draft",
    createdAt: "2026-06-12",
    updatedAt: "2026-06-07",
    coverImage: "placeholder-phone",
    thumbnail: "thumbnail-phone",
    productCount: 40,
    imageCount: 112,
  },
  {
    id: "project-020",
    name: "Premium Tea Collection",
    description: "Elegant product visuals for a premium tea storefront.",
    platform: "Shopify",
    language: "English",
    status: "Archived",
    createdAt: "2026-03-09",
    updatedAt: "2026-06-06",
    coverImage: "placeholder-tea",
    thumbnail: "thumbnail-tea",
    productCount: 17,
    imageCount: 57,
  },
];
